name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build & Test
    runs-on: macos-arm64

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Swift version
        run: swift --version

      - name: Build (debug)
        run: swift build

      - name: Test
        run: swift test
